// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"

	"github.com/google/uuid"
)

type Campaigns struct {
	ID           int64  `json:"id"`
	Image        string `json:"image"`
	CampaignName string `json:"campaign_name"`
}

type Donations struct {
	ID           int64     `json:"id"`
	Owner        string    `json:"owner"`
	Title        string    `json:"title"`
	CampaignType string    `json:"campaign_type"`
	Description  string    `json:"description"`
	Goal         int64     `json:"goal"`
	Deadline     time.Time `json:"deadline"`
	Image        string    `json:"image"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserSession struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Users struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Avatar            string    `json:"avatar"`
	Email             string    `json:"email"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Balance           string    `json:"balance"`
	IsBiomatric       bool      `json:"isBiomatric"`
	Address           string    `json:"address"`
	FilePath          string    `json:"file_path"`
	SecretCode        string    `json:"secret_code"`
	IsUsed            bool      `json:"is_used"`
	CreatedAt         time.Time `json:"created_at"`
	ExpiredAt         time.Time `json:"expired_at"`
}
